### PR TITLE
added language german

### PR DESCRIPTION
**Pull request by Eisbaeeer**
Added language german

### CODE REVIEW

**Comment by maakbaas** [comment]
Thanks for the pull request. I don't think it is necessary to add the html encoding. When I try your example file the codes like `&uuml;` are displayed directly in the interface. 

Did you test this, and if the behavior is the same on your side, can you adjust it to normal text?

**Comment by Eisbaeeer** [comment]
I will check this in processor and edit it if necessary. Actually not transfered to processor. Will come back later.

**Comment by maakbaas** [comment]
> I will check this in processor and edit it if necessary. Actually not transfered to processor. Will come back later.

If by any chance you will have some time this week to fix this PR, I can incorporate the German language in the next release :).

**Comment by Eisbaeeer** [comment]
I will do my best.

**Pull request merged**
